# SQL RESULTS - Customers

## 1.0 Import necessary libraries

In [1]:
# Data analysis
import pandas as pd

# Directory
from pathlib import Path

## 2.0 Paths setup

In [2]:
# Current directory
CURRENT_DIR = Path.cwd()

# Path to main folder
PROJECT_ROOT = CURRENT_DIR.parent.parent

# Path to folders and files
RESULTS_FOLDER = PROJECT_ROOT/"SQL_results"
CUSTOMER_ANALYSIS_RESULTS = RESULTS_FOLDER/"customer_analysis"

## 3.0 Customer Analysis

### 3.1 Total Customers

In [3]:
total_customers = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"total_customers.csv")
total_customers

   CustomerCount
0           5765

### 3.2 Top 10 customers by total sales

In [4]:
top_10_customers_sales = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"top_10_customers_sales.csv")
top_10_customers_sales

   CustomerID         Country  TotalSales  CustomerLifetimeDays  OrdersRank
0       14646     Netherlands   280206.02                   353           8
1       18102  United Kingdom   259657.30                   367          11
2       17450  United Kingdom   194390.79                   359          20
3       16446  United Kingdom   168472.50                   205        2623
4       14911            EIRE   143711.17                   372           2
5       12415       Australia   124914.53                   313          95
6       14156            EIRE   117210.08                   362          14
7       17511  United Kingdom    91062.38                   371          42
8       16029  United Kingdom    80850.84                   335           9
9       12346  United Kingdom    77183.60                     0        4700

### 3.3 Bottom 10 customers by total sales

In [5]:
bottom_10_customers_sales = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"bottom_10_customers_sales.csv")
bottom_10_customers_sales

  CustomerID         Country  TotalSales  CustomerLifetimeDays  OrdersRank
0    539441I  United Kingdom        0.42                     0        4649
1    573589I  United Kingdom        0.55                     0        5501
2    540833I  United Kingdom        0.65                     0        3049
3    560217I  United Kingdom        0.79                     0        5145
4    546876I  United Kingdom        0.84                     0        3223
5    549534I  United Kingdom        0.84                     0        2958
6    542136I  United Kingdom        0.84                     0        3189
7    544927I  United Kingdom        0.85                     0        3302
8    544438I  United Kingdom        0.85                     0        3367
9    551538I  United Kingdom        0.85                     0        3900

### 3.4 Top 10 customers by total orders

In [6]:
top_10_customers_orders = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"top_10_customers_orders.csv")
top_10_customers_orders

   CustomerID         Country  TotalOrders  CustomerLifetimeDays  SalesRank
0       12748  United Kingdom          209                   373         31
1       14911            EIRE          201                   372          5
2       17841  United Kingdom          124                   372         25
3       13089  United Kingdom           97                   367         15
4       14606  United Kingdom           93                   372         90
5       15311  United Kingdom           91                   373         14
6       12971  United Kingdom           86                   369         96
7       14646     Netherlands           73                   353          1
8       16029  United Kingdom           63                   335          9
9       13408  United Kingdom           62                   372         37

### 3.5 Bottom 10 customers by total orders

In [7]:
bottom_10_customers_orders = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"bottom_10_customers_orders.csv")
bottom_10_customers_orders

  CustomerID         Country  TotalOrders  CustomerLifetimeDays  SalesRank
0    543201I  United Kingdom            1                     0       2720
1      14222  United Kingdom            1                     0       2727
2    550214I  United Kingdom            1                     0       2715
3    544201I  United Kingdom            1                     0       2734
4      12478          Greece            1                     0       2732
5    542624I  United Kingdom            1                     0       2742
6      15322  United Kingdom            1                     0       2737
7      16377  United Kingdom            1                     0       2745
8      12658         Germany            1                     0       2722
9      18082  United Kingdom            1                     0       2733

### 3.6 Total customers per country

In [8]:
customers_per_country = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"customers_per_country.csv")

customers_per_country

                 Country  CustomerCount
0         United Kingdom           5292
1                Germany             94
2                 France             90
3                   EIRE             31
4                  Spain             30
5                Belgium             25
6            Switzerland             24
7               Portugal             20
8                  Italy             14
9                Finland             12
10             Hong Kong             11
11               Austria             11
12                Norway             10
13               Denmark              9
14       Channel Islands              9
15           Netherlands              9
16           Unspecified              9
17             Australia              9
18                 Japan              8
19                Cyprus              8
20                Sweden              8
21                Israel              6
22                Poland              6
23                Greece              4
24                Canada              4
25                   USA              4
26               Bahrain              3
27  United Arab Emirates              2
28                 Malta              2
29          Saudi Arabia              1
30             Singapore              1
31               Iceland              1
32               Lebanon              1
33        Czech Republic              1
34                Brazil              1
35    European Community              1
36             Lithuania              1
37                   RSA              1

In [9]:
# Column for percentage of customers from the UK
UK_Customers = (customers_per_country[customers_per_country['Country']=='United Kingdom']['CustomerCount'] / total_customers['CustomerCount']) * 100

print(f'Percentage of customers from United Kingdom: {UK_Customers}')

Percentage of customers from United Kingdom: 0    91.795317
Name: CustomerCount, dtype: float64

### 3.7 Top customer per country by total sales

In [10]:
# Last purchase date - first purchaase date = customerlifetimedays
customer_sales_country = pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"top_customer_sales_per_country.csv")
customer_sales_country

                 Country CustomerID  CustomerLifetimeDays  TotalSales
0            Netherlands      14646                   353   280206.02
1         United Kingdom      18102                   367   259657.30
2                   EIRE      14911                   372   143711.17
3              Australia      12415                   313   124914.53
4                 Sweden      17404                   356    31906.82
5                  Japan      12753                   340    21429.39
6              Singapore      12744                   267    21279.29
7                Germany      12471                   362    19788.65
8                 France      12731                   341    18895.91
9                  Spain      12540                   342    13400.24
10                Norway      12433                   373    13375.87
11           Switzerland      12409                   104    11072.67
12       Channel Islands      14936                   242     8137.02
13               Finland      12428                   258     7956.46
14              Portugal      12757                   196     7834.65
15               Denmark      12435                   188     7829.89
16                Cyprus      12359                   274     6310.03
17               Belgium      12362                   292     5226.23
18                Israel      12688                     0     4873.81
19               Iceland      12347                   365     4310.00
20                Poland      12779                   334     3981.36
21                 Italy      12594                   285     3338.22
22                Canada      17444                    25     2940.04
23               Austria      12360                   148     2662.06
24                Greece      14439                     0     2661.24
25             Hong Kong    564087I                     0     2653.95
26                 Malta      17828                   162     1820.09
27               Lebanon      12764                     0     1693.88
28             Lithuania      15332                     3     1661.06
29                   USA      12607                     0     1579.51
30    European Community      15108                    86     1300.25
31                Brazil      12769                     0     1143.60
32           Unspecified      16320                    41     1038.46
33  United Arab Emirates      12739                    21     1013.04
34                   RSA      12446                     0     1002.31
35        Czech Republic      12781                   221      826.74
36               Bahrain      12355                     0      459.40
37          Saudi Arabia      12565                     0      145.92

### 3.8 Top customer per country by total orders

In [11]:
customer_orders_country= pd.read_csv(CUSTOMER_ANALYSIS_RESULTS/"top_customer_orders_per_country.csv")
customer_orders_country

                 Country CustomerID  CustomerLifetimeDays  TotalOrders
0         United Kingdom      12748                   373          209
1                   EIRE      14911                   372          201
2            Netherlands      14646                   353           73
3                Germany      12569                   250           32
4                 France      12682                   368           31
5              Australia      12415                   313           21
6                  Spain      12540                   342           17
7                 Sweden      17404                   356           15
8               Portugal      12757                   196           13
9                Belgium      12395                   352           12
10                 Italy      12594                   285           10
11               Finland      12664                   314            9
12       Channel Islands      14936                   242            8
13                Norway      12352                   260            8
14                Poland      12779                   334            8
15               Iceland      12347                   365            7
16             Singapore      12744                   267            7
17                 Japan      12753                   340            6
18           Switzerland      13520                   313            6
19                Cyprus      12359                   274            4
20    European Community      15108                    86            4
21             Lithuania      15332                     3            4
22                 Malta      17828                   162            4
23               Austria      12414                    93            3
24                Canada      17444                    25            3
25               Denmark      12429                   356            3
26           Unspecified      16320                    41            2
27                   USA      12646                    45            2
28        Czech Republic      12781                   221            2
29                Greece      12717                    94            2
30                Israel      12512                     0            2
31  United Arab Emirates      12739                    21            2
32               Bahrain      12355                     0            1
33                Brazil      12769                     0            1
34             Hong Kong    553148I                     0            1
35               Lebanon      12764                     0            1
36                   RSA      12446                     0            1
37          Saudi Arabia      12565                     0            1