# SQL Results - Products

## 1.0 Import necessary libraries

In [1]:
# Data analysis
import pandas as pd

# Directory
from pathlib import Path

In [2]:
## 2.0 Paths setup

In [3]:
# Current directory
CURRENT_DIR = Path.cwd()

# Path to main folder
PROJECT_ROOT = CURRENT_DIR.parent.parent

# Path to folders
RESULTS_FOLDER = PROJECT_ROOT/"SQL_results"
PRODUCT_ANALYSIS_RESULTS = RESULTS_FOLDER/"product_analysis"

## 3.0 Product Analysis

### 3.1 Total distinct products

In [4]:
total_distinct_products = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"total_distinct_products.csv")
total_distinct_products

   Unnamed: 0
0       66609

### 3.2 Top 10 products by sales

In [5]:
top_10_products_sales = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"top_10_products_sales.csv")
top_10_products_sales

  StockCode                  ProductDescription  ProductTotal
0       DOT                      DOTCOM POSTAGE     206248.77
1     22423            REGENCY CAKESTAND 3 TIER     174156.54
2     23843         PAPER CRAFT , LITTLE BIRDIE     168469.60
3    85123A  WHITE HANGING HEART T-LIGHT HOLDER     106415.23
4     47566                       PARTY BUNTING      99445.23
5    85099B             JUMBO BAG RED RETROSPOT      94159.81
6     23166      MEDIUM CERAMIC TOP STORAGE JAR      81700.92
7      POST                             POSTAGE      78101.88
8         M                              Manual      77752.82
9     23084                  RABBIT NIGHT LIGHT      66870.03

### 3.3 Bottom 10 products by sale

In [6]:
bottom_10_products_sales = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"bottom_10_products_sales.csv")
bottom_10_products_sales

  StockCode                   ProductDescription  ProductTotal
0      PADS           PADS TO MATCH ALL CUSHIONS          0.00
1     84227            HEN HOUSE W CHICK IN NEST          0.42
2     21268             VINTAGE BLUE TINSEL REEL          0.84
3     90084      PINK CRYSTAL GUITAR PHONE CHARM          0.85
4    84206B       CAT WITH SUNGLASSES BLANK CARD          0.95
5    84201C       HAPPY BIRTHDAY CARD TEDDY/CAKE          0.95
6     84990  60 GOLD AND SILVER FAIRY CAKE CASES          1.10
7     37461                     FUNKY MONKEY MUG          1.25
8    84743C           ORANGE FELT VASE + FLOWERS          1.25
9     84977           WIRE FLOWER T-LIGHT HOLDER          1.25

### 3.4 Top 10 products by quantity

In [7]:
top_10_products_quantity = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"top_10_products_quantity.csv")
top_10_products_quantity

  StockCode                  ProductDescription  ProductQuantity
0     23843         PAPER CRAFT , LITTLE BIRDIE            80995
1     23166      MEDIUM CERAMIC TOP STORAGE JAR            78033
2     22197                SMALL POPCORN HOLDER            56898
3     84077   WORLD WAR 2 GLIDERS ASSTD DESIGNS            54951
4    85099B             JUMBO BAG RED RETROSPOT            48371
5    85123a  WHITE HANGING HEART T-LIGHT HOLDER            37933
6     21212     PACK OF 72 RETROSPOT CAKE CASES            36396
7     84879       ASSORTED COLOUR BIRD ORNAMENT            36362
8     23084                  RABBIT NIGHT LIGHT            30739
9     22492             MINI PAINT SET VINTAGE             26633

### 3.5 Bottom 10 products by quantity

In [8]:
bottom_10_products_quantity = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"bottom_10_products_quantity.csv")
bottom_10_products_quantity

  StockCode                   ProductDescription  ProductQuantity
0     23602        SET 10 CARDS 3 WISE MEN 17107                1
1    35609A    PINK FEATHER CHRISTMAS DECORATION                1
2     22146   EASTER CRAFT IVY WREATH WITH CHICK                1
3     37474  SET/4 2 TONE EGG SHAPE MIXING BOWLS                1
4     35650        VINTAGE BEAD PINK JEWEL STAND                1
5    84743C           ORANGE FELT VASE + FLOWERS                1
6     20703              BLUE PADDED SOFT MOBILE                1
7     84977           WIRE FLOWER T-LIGHT HOLDER                1
8     23628   SET 10 CARDS TRIANGLE ICONS  17220                1
9     37461                     FUNKY MONKEY MUG                1

### 3.6 Top 3 products per month by sales

In [9]:
top_3_per_month_by_sales = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"top_3_per_month_by_sales.csv")
top_3_per_month_by_sales

   OrderMonth  StockCode                   ProductDescription  ProductTotal
0     2010-12      22423             REGENCY CAKESTAND 3 TIER      25929.56
1     2010-12        DOT                       DOTCOM POSTAGE      24671.19
2     2010-12  AMAZONFEE                           AMAZON FEE      13541.33
3     2011-01      23166       MEDIUM CERAMIC TOP STORAGE JAR      77183.60
4     2011-01     85123a   WHITE HANGING HEART T-LIGHT HOLDER      14499.55
5     2011-01        DOT                       DOTCOM POSTAGE      13921.82
6     2011-02        DOT                       DOTCOM POSTAGE      10060.57
7     2011-02      22423             REGENCY CAKESTAND 3 TIER       8438.64
8     2011-02      21623         VINTAGE UNION JACK MEMOBOARD       6810.39
9     2011-03      22423             REGENCY CAKESTAND 3 TIER      16320.15
10    2011-03        DOT                       DOTCOM POSTAGE      11829.71
11    2011-03     85099B              JUMBO BAG RED RETROSPOT       9717.43
12    2011-04      22423             REGENCY CAKESTAND 3 TIER      13828.35
13    2011-04      47566                        PARTY BUNTING      10669.57
14    2011-04     85123A   WHITE HANGING HEART T-LIGHT HOLDER       9973.54
15    2011-05      47566                        PARTY BUNTING      18238.15
16    2011-05     85123A   WHITE HANGING HEART T-LIGHT HOLDER      11174.42
17    2011-05      22423             REGENCY CAKESTAND 3 TIER      10269.22
18    2011-06      22502       PICNIC BASKET WICKER 60 PIECES      39619.50
19    2011-06        DOT                       DOTCOM POSTAGE      11848.66
20    2011-06      47566                        PARTY BUNTING      11804.52
21    2011-07      47566                        PARTY BUNTING      13812.80
22    2011-07        DOT                       DOTCOM POSTAGE      12841.00
23    2011-07      22423             REGENCY CAKESTAND 3 TIER      11546.61
24    2011-08        DOT                       DOTCOM POSTAGE      13400.52
25    2011-08      84879        ASSORTED COLOUR BIRD ORNAMENT       9774.09
26    2011-08     85099B              JUMBO BAG RED RETROSPOT       9199.24
27    2011-09        DOT                       DOTCOM POSTAGE      15177.40
28    2011-09      23243  SET OF TEA COFFEE SUGAR TINS PANTRY       9524.81
29    2011-09     85099B              JUMBO BAG RED RETROSPOT       8230.97
30    2011-10        DOT                       DOTCOM POSTAGE      17955.13
31    2011-10      23284        DOORMAT KEEP CALM AND COME IN      11333.40
32    2011-10      22086      PAPER CHAIN KIT 50'S CHRISTMAS        9743.54
33    2011-11        DOT                       DOTCOM POSTAGE      36905.40
34    2011-11      22086      PAPER CHAIN KIT 50'S CHRISTMAS       28225.99
35    2011-11      23084                   RABBIT NIGHT LIGHT      23159.84
36    2011-12      23843          PAPER CRAFT , LITTLE BIRDIE     168469.60
37    2011-12        DOT                       DOTCOM POSTAGE      19872.69
38    2011-12      22086      PAPER CHAIN KIT 50'S CHRISTMAS        6850.06

#### 3.6.1 Count of distinct products in 'top_3_per_month_by_sales'

In [10]:
top_product_monthly_sales = top_3_per_month_by_sales.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count')
).reset_index().sort_values('No_of_times', ascending=False)
print(top_product_monthly_sales)

                     ProductDescription  No_of_times
3                        DOTCOM POSTAGE           11
11             REGENCY CAKESTAND 3 TIER            6
8                         PARTY BUNTING            4
4               JUMBO BAG RED RETROSPOT            3
14   WHITE HANGING HEART T-LIGHT HOLDER            3
6       PAPER CHAIN KIT 50'S CHRISTMAS             3
2         DOORMAT KEEP CALM AND COME IN            1
5        MEDIUM CERAMIC TOP STORAGE JAR            1
0                            AMAZON FEE            1
1         ASSORTED COLOUR BIRD ORNAMENT            1
7           PAPER CRAFT , LITTLE BIRDIE            1
10                   RABBIT NIGHT LIGHT            1
9        PICNIC BASKET WICKER 60 PIECES            1
12  SET OF TEA COFFEE SUGAR TINS PANTRY            1
13         VINTAGE UNION JACK MEMOBOARD            1

### 3.7 Bottom 3 products per month by sales

In [11]:
bottom_3_per_month_by_sales = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"bottom_3_per_month_by_sales.csv")
bottom_3_per_month_by_sales

   OrderMonth StockCode                   ProductDescription  ProductTotal
0     2010-12     21986     PACK OF 12 PINK POLKADOT TISSUES          0.29
1     2010-12     21985    PACK OF 12 HEARTS DESIGN TISSUES           0.29
2     2010-12    79149B              SILICON STAR BULB  BLUE          0.42
3     2011-01     44234             ASSORTED CIRCULAR MOBILE          0.42
4     2011-01     17174               ASSTD RASTA KEY-CHAINS          0.42
5     2011-01     22153      ANGEL DECORATION STARS ON DRESS          0.42
6     2011-02     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS          0.29
7     2011-02     22531  MAGIC DRAWING SLATE CIRCUS PARADE            0.42
8     2011-02     22536           MAGIC DRAWING SLATE PURDEY          0.42
9     2011-03    35607B   BLACK FEATHER CHRISTMAS DECORATION          0.19
10    2011-03     22999      TRAVEL CARD WALLET RETRO PETALS          0.42
11    2011-03     22997        TRAVEL CARD WALLET UNION JACK          0.42
12    2011-04      PADS           PADS TO MATCH ALL CUSHIONS          0.00
13    2011-04    37444A      YELLOW BREAKFAST CUP AND SAUCER          0.39
14    2011-04     23003     TRAVEL CARD WALLET VINTAGE ROSE           0.42
15    2011-05    37479P        CUBIC MUG FLOCK PINK ON BROWN          0.39
16    2011-05     37468               HARDMAN MUG 3 ASSORTED          0.39
17    2011-05     22546                   MINI JIGSAW PURDEY          0.42
18    2011-06     47420     ASSORTED COLOUR SUCTION CUP HOOK          0.19
19    2011-06     79337        BLUE FLOCK GLASS CANDLEHOLDER          0.38
20    2011-06    37489A    YELLOW/PINK FLOWER DESIGN BIG MUG          0.39
21    2011-07      PADS           PADS TO MATCH ALL CUSHIONS          0.00
22    2011-07    37462E                    PET MUG, GOLDFISH          0.19
23    2011-07    79063C    RETRO PILL BOX KEY CHAIN,THE KING          0.19
24    2011-08     22267         EASTER DECORATION EGG BUNNY           0.39
25    2011-08    79149B              SILICON STAR BULB  BLUE          0.42
26    2011-08     22533     MAGIC DRAWING SLATE BAKE A CAKE           0.42
27    2011-09      PADS           PADS TO MATCH ALL CUSHIONS          0.00
28    2011-09    84251B         GREETING CARD, STICKY GORDON          0.19
29    2011-09     84199                GLOW IN DARK DOLPHINS          0.21
30    2011-10    79063D       RETRO PILL BOX , REVOLUTIONARY          0.19
31    2011-10     37468               HARDMAN MUG 3 ASSORTED          0.39
32    2011-10     22541                MINI JIGSAW LEAP FROG          0.42
33    2011-11    84201B    HAPPY BIRTHDAY CARD STRIPEY TEDDY          0.19
34    2011-11     21402                      RED  EGG  SPOON          0.36
35    2011-11     21403                      BLUE EGG  SPOON          0.36
36    2011-12     47420     ASSORTED COLOUR SUCTION CUP HOOK          0.19
37    2011-12    79063C    RETRO PILL BOX KEY CHAIN,THE KING          0.19
38    2011-12     22753      SMALL YELLOW BABUSHKA NOTEBOOK           0.21

#### 3.7.1 Count of distinct products in 'bottom_3_per_month_by_sales'

In [12]:
bottom_products_monthly_sales = bottom_3_per_month_by_sales.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count')
).reset_index().sort_values('No_of_times', ascending=True)
print(bottom_products_monthly_sales)

                     ProductDescription  No_of_times
0       ANGEL DECORATION STARS ON DRESS            1
1              ASSORTED CIRCULAR MOBILE            1
3                ASSTD RASTA KEY-CHAINS            1
4    BLACK FEATHER CHRISTMAS DECORATION            1
6         BLUE FLOCK GLASS CANDLEHOLDER            1
5                       BLUE EGG  SPOON            1
7         CUBIC MUG FLOCK PINK ON BROWN            1
8          EASTER DECORATION EGG BUNNY             1
13     MAGIC DRAWING SLATE BAKE A CAKE             1
9                 GLOW IN DARK DOLPHINS            1
10         GREETING CARD, STICKY GORDON            1
11    HAPPY BIRTHDAY CARD STRIPEY TEDDY            1
15           MAGIC DRAWING SLATE PURDEY            1
14  MAGIC DRAWING SLATE CIRCUS PARADE              1
17                   MINI JIGSAW PURDEY            1
16                MINI JIGSAW LEAP FROG            1
30    WORLD WAR 2 GLIDERS ASSTD DESIGNS            1
26      SMALL YELLOW BABUSHKA NOTEBOOK             1
18    PACK OF 12 HEARTS DESIGN TISSUES             1
19     PACK OF 12 PINK POLKADOT TISSUES            1
21                    PET MUG, GOLDFISH            1
22                      RED  EGG  SPOON            1
23       RETRO PILL BOX , REVOLUTIONARY            1
27      TRAVEL CARD WALLET RETRO PETALS            1
31      YELLOW BREAKFAST CUP AND SAUCER            1
28        TRAVEL CARD WALLET UNION JACK            1
29     TRAVEL CARD WALLET VINTAGE ROSE             1
32    YELLOW/PINK FLOWER DESIGN BIG MUG            1
12               HARDMAN MUG 3 ASSORTED            2
24    RETRO PILL BOX KEY CHAIN,THE KING            2
25              SILICON STAR BULB  BLUE            2
2      ASSORTED COLOUR SUCTION CUP HOOK            2
20           PADS TO MATCH ALL CUSHIONS            3

### 3.8 Top 3 products per month by quantity

In [13]:
top_3_per_month_by_quantity = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"top_3_per_month_by_quantity.csv")
top_3_per_month_by_quantity

   OrderMonth StockCode                   ProductDescription  ProductQuantity
0     2010-12     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS             4571
1     2010-12    85123a   WHITE HANGING HEART T-LIGHT HOLDER             3751
2     2010-12     22834          HAND WARMER BABUSHKA DESIGN             3296
3     2011-01     23166       MEDIUM CERAMIC TOP STORAGE JAR            74215
4     2011-01    85123a   WHITE HANGING HEART T-LIGHT HOLDER             5243
5     2011-01     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR             3228
6     2011-02     22053                EMPIRE DESIGN ROSETTE             3976
7     2011-02     22693   GROW A FLYTRAP OR SUNFLOWER IN TIN             3747
8     2011-02     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS             3469
9     2011-03    85099B              JUMBO BAG RED RETROSPOT             5059
10    2011-03     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS             3744
11    2011-03     22616           PACK OF 12 LONDON TISSUES              3465
12    2011-04     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS             9567
13    2011-04    85123A   WHITE HANGING HEART T-LIGHT HOLDER             3828
14    2011-04     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR             3136
15    2011-05     22197                 SMALL POPCORN HOLDER             6721
16    2011-05     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS             4181
17    2011-05    85123A   WHITE HANGING HEART T-LIGHT HOLDER             3950
18    2011-06    85099B              JUMBO BAG RED RETROSPOT             3159
19    2011-06     17003                  BROCADE RING PURSE              2990
20    2011-06     15036            ASSORTED COLOURS SILK FAN             2926
21    2011-07     84568      GIRLS ALPHABET IRON ON PATCHES              3579
22    2011-07     15036            ASSORTED COLOURS SILK FAN             3462
23    2011-07     18007  ESSENTIAL BALM 3.5g TIN IN ENVELOPE             3207
24    2011-08     84879        ASSORTED COLOUR BIRD ORNAMENT             6489
25    2011-08     22197                       POPCORN HOLDER             5135
26    2011-08    85099B              JUMBO BAG RED RETROSPOT             4648
27    2011-09    85099B              JUMBO BAG RED RETROSPOT             4059
28    2011-09     22197                       POPCORN HOLDER             3756
29    2011-09     22952      60 CAKE CASES VINTAGE CHRISTMAS             2918
30    2011-10     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS             7988
31    2011-10     22197                       POPCORN HOLDER             5168
32    2011-10    85099B              JUMBO BAG RED RETROSPOT             4899
33    2011-11     22197                       POPCORN HOLDER            12030
34    2011-11     23084                   RABBIT NIGHT LIGHT             8675
35    2011-11     22086      PAPER CHAIN KIT 50'S CHRISTMAS              7629
36    2011-12     23843          PAPER CRAFT , LITTLE BIRDIE            80995
37    2011-12     22197                       POPCORN HOLDER             6021
38    2011-12     23084                   RABBIT NIGHT LIGHT             2396

#### 3.8.1 Count of distinct products in 'top_3_per_month_by_quantity'

In [14]:
top_products_monthly_quantity = top_3_per_month_by_quantity.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count')
).reset_index().sort_values('No_of_times', ascending=False)
print(top_products_monthly_quantity)

                     ProductDescription  No_of_times
19    WORLD WAR 2 GLIDERS ASSTD DESIGNS            6
10              JUMBO BAG RED RETROSPOT            5
15                       POPCORN HOLDER            5
18   WHITE HANGING HEART T-LIGHT HOLDER            4
16                   RABBIT NIGHT LIGHT            2
6    FAIRY CAKE FLANNEL ASSORTED COLOUR            2
2             ASSORTED COLOURS SILK FAN            2
0       60 CAKE CASES VINTAGE CHRISTMAS            1
3                   BROCADE RING PURSE             1
1         ASSORTED COLOUR BIRD ORNAMENT            1
5   ESSENTIAL BALM 3.5g TIN IN ENVELOPE            1
4                 EMPIRE DESIGN ROSETTE            1
11       MEDIUM CERAMIC TOP STORAGE JAR            1
9           HAND WARMER BABUSHKA DESIGN            1
8    GROW A FLYTRAP OR SUNFLOWER IN TIN            1
7       GIRLS ALPHABET IRON ON PATCHES             1
14          PAPER CRAFT , LITTLE BIRDIE            1
13      PAPER CHAIN KIT 50'S CHRISTMAS             1
12           PACK OF 12 LONDON TISSUES             1
17                 SMALL POPCORN HOLDER            1

### 3.9 Bottom 3 products per month by quantity

In [15]:
bottom_3_per_month_by_quantity = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"bottom_3_per_month_by_quantity.csv")
bottom_3_per_month_by_quantity

   OrderMonth StockCode                  ProductDescription  ProductQuantity
0     2010-12     21986    PACK OF 12 PINK POLKADOT TISSUES                1
1     2010-12     21985   PACK OF 12 HEARTS DESIGN TISSUES                 1
2     2010-12     71215              METAL BASE FOR CANDLES                1
3     2011-01     17174              ASSTD RASTA KEY-CHAINS                1
4     2011-01     22153     ANGEL DECORATION STARS ON DRESS                1
5     2011-01     44234            ASSORTED CIRCULAR MOBILE                2
6     2011-02     84077   WORLD WAR 2 GLIDERS ASSTD DESIGNS                1
7     2011-02     22532      MAGIC DRAWING SLATE LEAP FROG                 1
8     2011-02     22489      PACK OF 12 TRADITIONAL CRAYONS                1
9     2011-03    35607B  BLACK FEATHER CHRISTMAS DECORATION                1
10    2011-03     23000        TRAVEL CARD WALLET TRANSPORT                1
11    2011-03     84227           HEN HOUSE W CHICK IN NEST                1
12    2011-04    37444A     YELLOW BREAKFAST CUP AND SAUCER                1
13    2011-04      PADS          PADS TO MATCH ALL CUSHIONS                1
14    2011-04     23003    TRAVEL CARD WALLET VINTAGE ROSE                 1
15    2011-05     22546                  MINI JIGSAW PURDEY                1
16    2011-05    37479P       CUBIC MUG FLOCK PINK ON BROWN                1
17    2011-05     37468              HARDMAN MUG 3 ASSORTED                1
18    2011-06     47420    ASSORTED COLOUR SUCTION CUP HOOK                1
19    2011-06    37489A   YELLOW/PINK FLOWER DESIGN BIG MUG                1
20    2011-06     79337       BLUE FLOCK GLASS CANDLEHOLDER                1
21    2011-07    37462E                   PET MUG, GOLDFISH                1
22    2011-07      PADS          PADS TO MATCH ALL CUSHIONS                1
23    2011-07    79063C   RETRO PILL BOX KEY CHAIN,THE KING                1
24    2011-08     22267        EASTER DECORATION EGG BUNNY                 1
25    2011-08    79149B             SILICON STAR BULB  BLUE                1
26    2011-08     22533    MAGIC DRAWING SLATE BAKE A CAKE                 1
27    2011-09      PADS          PADS TO MATCH ALL CUSHIONS                1
28    2011-09     84199               GLOW IN DARK DOLPHINS                1
29    2011-09    84251B        GREETING CARD, STICKY GORDON                1
30    2011-10     22541               MINI JIGSAW LEAP FROG                1
31    2011-10    79063D      RETRO PILL BOX , REVOLUTIONARY                1
32    2011-10     37468              HARDMAN MUG 3 ASSORTED                1
33    2011-11    84201B   HAPPY BIRTHDAY CARD STRIPEY TEDDY                1
34    2011-11     21402                     RED  EGG  SPOON                3
35    2011-11     21403                     BLUE EGG  SPOON                3
36    2011-12     22755     SMALL PURPLE BABUSHKA NOTEBOOK                 1
37    2011-12     47420    ASSORTED COLOUR SUCTION CUP HOOK                1
38    2011-12    79063C   RETRO PILL BOX KEY CHAIN,THE KING                1

#### 3.9.1 Count of distinct products in 'bottom_3_per_month_by_quantity'

In [16]:
bottom_products_monthly_quantity = bottom_3_per_month_by_quantity.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count')
).reset_index().sort_values('No_of_times', ascending=True)
print(bottom_products_monthly_quantity)

                    ProductDescription  No_of_times
0      ANGEL DECORATION STARS ON DRESS            1
1             ASSORTED CIRCULAR MOBILE            1
3               ASSTD RASTA KEY-CHAINS            1
4   BLACK FEATHER CHRISTMAS DECORATION            1
6        BLUE FLOCK GLASS CANDLEHOLDER            1
5                      BLUE EGG  SPOON            1
7        CUBIC MUG FLOCK PINK ON BROWN            1
8         EASTER DECORATION EGG BUNNY             1
13           HEN HOUSE W CHICK IN NEST            1
9                GLOW IN DARK DOLPHINS            1
10        GREETING CARD, STICKY GORDON            1
11   HAPPY BIRTHDAY CARD STRIPEY TEDDY            1
15      MAGIC DRAWING SLATE LEAP FROG             1
14    MAGIC DRAWING SLATE BAKE A CAKE             1
17               MINI JIGSAW LEAP FROG            1
16              METAL BASE FOR CANDLES            1
30    TRAVEL CARD WALLET VINTAGE ROSE             1
25      RETRO PILL BOX , REVOLUTIONARY            1
18                  MINI JIGSAW PURDEY            1
19   PACK OF 12 HEARTS DESIGN TISSUES             1
20    PACK OF 12 PINK POLKADOT TISSUES            1
21      PACK OF 12 TRADITIONAL CRAYONS            1
23                   PET MUG, GOLDFISH            1
24                     RED  EGG  SPOON            1
31   WORLD WAR 2 GLIDERS ASSTD DESIGNS            1
29        TRAVEL CARD WALLET TRANSPORT            1
27             SILICON STAR BULB  BLUE            1
28     SMALL PURPLE BABUSHKA NOTEBOOK             1
33   YELLOW/PINK FLOWER DESIGN BIG MUG            1
32     YELLOW BREAKFAST CUP AND SAUCER            1
12              HARDMAN MUG 3 ASSORTED            2
2     ASSORTED COLOUR SUCTION CUP HOOK            2
26   RETRO PILL BOX KEY CHAIN,THE KING            2
22          PADS TO MATCH ALL CUSHIONS            3

### 3.10 Top 3 products per country by sales

In [17]:
top_3_per_country_by_sales = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"top_3_per_country_by_sales.csv")
top_3_per_country_by_sales

        Country StockCode                  ProductDescription  ProductTotal
0     Australia     23084                  RABBIT NIGHT LIGHT       2921.28
1     Australia     22940           FELTCRAFT CHRISTMAS FAIRY       1260.00
2     Australia     22722   SET OF 6 SPICE TINS PANTRY DESIGN       1242.00
3       Austria      POST                             POSTAGE        400.00
4       Austria     22582        PACK OF 6 SWEETIE GIFT BOXES        302.40
..          ...       ...                                 ...           ...
86  Unspecified     23236          STORAGE TIN VINTAGE DOILY          69.36
87  Unspecified     22960            JAM MAKING SET WITH JARS         45.00
88          USA     21122  SET/10 PINK POLKADOT PARTY CANDLES         90.00
89          USA     21124  SET/10 BLUE POLKADOT PARTY CANDLES         90.00
90          USA     21121   SET/10 RED POLKADOT PARTY CANDLES         90.00

[91 rows x 4 columns]

#### 3.10.1  Count of distinct products in 'top_3_per_country_by_sales'

In [18]:
import textwrap
top_product_country_sales = top_3_per_country_by_sales.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count'),
    Countries=('Country', lambda x: '\n'.join(textwrap.wrap(', '.join(sorted(x.unique())), width=50)))
).reset_index().sort_values('No_of_times', ascending=False)

top_product_country_sales.style.set_properties(**{'text-align': 'left'})

### 3.11 Bottom 3 products per country by sales

In [19]:
bottom_3_per_country_by_sales = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"bottom_3_per_country_by_sales.csv")
bottom_3_per_country_by_sales

         Country StockCode                  ProductDescription  ProductTotal
0      Australia     22545                 MINI JIGSAW BUNNIES          0.42
1      Australia     22546                  MINI JIGSAW PURDEY          0.42
2      Australia     21917     SET 12 KIDS  WHITE CHALK STICKS          0.42
3        Austria     21402                     RED  EGG  SPOON          2.88
4        Austria     21403                     BLUE EGG  SPOON          2.88
..           ...       ...                                 ...           ...
105  Unspecified     22396       MAGNETS PACK OF 4 RETRO PHOTO          0.39
106  Unspecified    47348A       FUSCHIA VOILE POINTY SHOE DEC          0.39
107          USA     22993        SET OF 4 PANTRY JELLY MOULDS          1.25
108          USA     22979             PANTRY WASHING UP BRUSH          2.90
109          USA     22965  3 TRADITIONAl BISCUIT CUTTERS  SET          4.20

[110 rows x 4 columns]

#### 3.11.1 Count of distinct products in 'bottom_3_per_country_by_sales'

In [20]:
bottom_product_country_sales = bottom_3_per_country_by_sales.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count'),
    Countries=('Country', lambda x: '\n'.join(textwrap.wrap(', '.join(sorted(x.unique())), width=50)))
).reset_index().sort_values('No_of_times', ascending=False)

bottom_product_country_sales.style.set_properties(**{'text-align': 'left'})

### 3.12 Top 3 products per country by quantity

In [21]:
top_3_per_country_by_quantity = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"top_3_per_country_by_quantity.csv")
top_3_per_country_by_quantity

,Country,StockCode,ProductDescription,ProductQuantity
0,Australia,23084,RABBIT NIGHT LIGHT,1632
1,Australia,22492,MINI PAINT SET VINTAGE,1152
2,Australia,21915,RED HARMONICA IN BOX,732
3,Austria,21918,SET 12 KIDS COLOUR CHALK STICKS,288
4,Austria,22546,MINI JIGSAW PURDEY,240
...,...,...,...,...
102,Unspecified,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,96
103,Unspecified,47021G,SET/6 BEAD COASTERS GAUZE BAG GOLD,48
104,USA,21121,SET/10 RED POLKADOT PARTY CANDLES,72
105,USA,21123,SET/10 IVORY POLKADOT PARTY CANDLES,72
106,USA,23366,SET 12 COLOURING PENCILS DOILY,72

#### 3.12.1 Count of distinct products in 'top_3_per_country_by_quantity'

In [22]:
top_product_country_quantity = top_3_per_country_by_quantity.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count'),
    Countries=('Country', lambda x: '\n'.join(textwrap.wrap(', '.join(sorted(x.unique())), width=50)))
).reset_index().sort_values('No_of_times', ascending=False)

top_product_country_quantity.style.set_properties(**{'text-align': 'left'})

### 3.13 Bottom 3 products per country by quantity

In [23]:
bottom_3_per_country_by_quantity = pd.read_csv(PRODUCT_ANALYSIS_RESULTS/"bottom_3_per_country_by_quantity.csv")
bottom_3_per_country_by_quantity

         Country StockCode                 ProductDescription  ProductQuantity
0      Australia     21936           RED RETROSPOT PICNIC BAG                1
1      Australia     23154           SET OF 4 JAM JAR MAGNETS                1
2      Australia     23209          LUNCH BAG DOILEY PATTERN                 1
3        Austria     22846         BREAD BIN DINER STYLE RED                 1
4        Austria     48188            DOORMAT WELCOME PUPPIES                2
..           ...       ...                                ...              ...
104  Unspecified     82600              NO SINGING METAL SIGN                1
105  Unspecified     84050    PINK HEART SHAPE EGG FRYING PAN                1
106          USA     22848         BREAD BIN DINER STYLE PINK                1
107          USA     22720  SET OF 3 CAKE TINS PANTRY DESIGN                 1
108          USA     22993       SET OF 4 PANTRY JELLY MOULDS                1

[109 rows x 4 columns]

#### 3.12.1 Count of distinct products in 'bottom_3_per_country_by_quantity'

In [24]:
bottom_product_country_quantity = bottom_3_per_country_by_quantity.groupby('ProductDescription').agg(
    No_of_times = ('ProductDescription', 'count'),
    Countries=('Country', lambda x: '\n'.join(textwrap.wrap(', '.join(sorted(x.unique())), width=50)))
).reset_index().sort_values('No_of_times', ascending=False)

bottom_product_country_quantity.style.set_properties(**{'text-align': 'left'})